export const Configurations = {
  profileImageSrc: 'assets/ProfilePic.svg',

  techStack: [
    'assets/logos_adobe-xd.svg',
    'assets/logos_figma.svg',
    'assets/logos_adobe-xd.svg',
    'assets/logos_adobe-xd.svg',
    'assets/logos_figma.svg',
    'assets/logos_adobe-xd.svg',
    'assets/logos_adobe-xd.svg',
    'assets/logos_figma.svg',
    'assets/logos_adobe-xd.svg',
    'assets/logos_adobe-xd.svg',
    'assets/logos_figma.svg',
    'assets/logos_adobe-xd.svg',
    'assets/logos_adobe-xd.svg',
    'assets/logos_figma.svg',
    'assets/logos_adobe-xd.svg',
    'assets/logos_adobe-xd.svg',
    'assets/logos_figma.svg',
    'assets/logos_adobe-xd.svg',
    'assets/logos_adobe-xd.svg',
    'assets/logos_figma.svg',
    'assets/logos_adobe-xd.svg',
    'assets/logos_adobe-xd.svg',
    'assets/logos_figma.svg',
    'assets/logos_adobe-xd.svg',
  ],

  socialInfo: [
    {
      imgSrcDarkTheme: 'assets/darkTheme_frontendmentor.svg',
      imgSrcLightTheme: 'assets/lightTheme_frontendmentor.svg',
      socialLink: 'https://www.frontendmentor.io/profile/SameemaNasrin',
    },
    {
      imgSrcDarkTheme: 'assets/darkTheme_github.svg',
      imgSrcLightTheme: 'assets/lightTheme_github.svg',
      socialLink: 'https://github.com/SameemaNasrin',
    },
    {
      imgSrcDarkTheme: 'assets/darkTheme_linkedin-square.svg',
      imgSrcLightTheme: 'assets/lightTheme_linkedin-square.svg',
      socialLink: 'https://www.linkedin.com/in/sameema-nasrin-3a435b170/',
    },
  ],

  otherThemeColor: ['#FF8274', '#FFED74', '#8BFF74', '#8274FF', '#EB49C3'],

  projects: [
    {
      name: 'TemplifyPro',
      logoImage: ' assets/Mockups/mockup 5.png',
      timeFrame: 'Personal Project - Dec 2024',
      projectDesc:
        'A template marketplace with Razorpay checkout, Firebase Authentication, and EmailJS contact form, offering a seamless shopping experience.',
      lock: false,
      leftText: 'Template',
      rightText: 'E-Commerce',
      technologies: [
        'Angular',
        'Angular Material',
        'HTML',
        'CSS',
        'JavaScript',
        'Firebase',
        'Razorpay',
        'MailJS',
      ],
      features: [
        'Template marketplace with Firebase database integration',
        'Razorpay integration for secure checkout',
        'EmailJS-powered contact form',
        'Firebase Authentication for user login and signup',
      ],
      challengePlatform: 'Personal Project',
      url: 'https://sameemanasrin.github.io/templify-pro/',
    },
    {
      name: 'Dzinr',
      logoImage: ' assets/Mockups/mockup 4.png',
      timeFrame: 'Personal Project - Nov 2024',
      projectDesc:
        'A fully responsive freelance design and dev studio with a ninja-themed layout and integrated contact form.',
      lock: false,
      leftText: 'Web Development',
      rightText: 'UI/UX Design',
      technologies: [
        'Angular',
        'Angular Material',
        'HTML',
        'CSS',
        'JavaScript',
        'EmailJS',
      ],
      features: [
        'Ninja-themed layout with dynamic user interface',
        'Responsive design for seamless device experience',
        "EmailJS-powered 'Contact Us' form",
      ],
      challengePlatform: 'Personal Project',
      url: 'https://sameemanasrin.github.io/dzinr/',
    },
    {
      name: 'Bubbles',
      logoImage: ' assets/Mockups/mockup 3.png',
      timeFrame: 'Personal Project - Oct 2024',
      projectDesc:
        'A freelance studio portfolio built with Angular featuring snap scrolling, bubble animations, and EmailJS contact form.',
      lock: false,
      leftText: 'Design & Dev',
      rightText: 'Studio',
      technologies: [
        'Angular',
        'Angular Material',
        'HTML',
        'CSS',
        'JavaScript',
        'EmailJS',
      ],
      features: [
        'Snap scroll navigation for smooth user experience',
        'Bubble animations using basic JavaScript',
        'EmailJS integration for contact form',
        'Responsive layout with dynamic UI',
      ],
      challengePlatform: 'Personal Project',
      url: 'https://sameemanasrin.github.io/bubbles/',
    },

    {
      name: 'Multi-Step Form',
      logoImage: ' assets/Mockups/mockup 2.png',
      timeFrame: 'Frontend Mentor - May 2023',
      projectDesc:
        'A fully responsive multi-step form with interactive elements, validation, and summary display, optimized for all devices.',
      lock: false,
      leftText: 'Form',
      rightText: 'Development',
      technologies: ['HTML', 'CSS', 'JavaScript'],
      features: [
        'Multi-step navigation with back and forward options',
        'Dynamic summary display of user selections',
        'Responsive layout for various screen sizes',
        'Hover and focus states for interactive elements',
        'Comprehensive form validation for missing fields, incorrect email format, and unselected options',
      ],
      challengePlatform: 'Frontend Mentor',
      url: 'https://sameemanasrin.github.io/multi-step-form/',
    },
    {
      name: 'ROCK PAPER SCISSORS LIZARD SPOCK',
      logoImage: 'assets/Mockups/mockup 1.png',
      timeFrame: 'Frontend Mentor - Apr 2023',
      projectDesc:
        'A fun, responsive game featuring real-time scoring, dynamic UI, and smooth, engaging animations.',
      lock: false,
      leftText: 'Game',
      rightText: 'Development',
      technologies: ['HTML', 'CSS', 'JavaScript'],
      features: [
        'Responsive Design',
        'Real-Time Scoring',
        'Interactive Animations',
      ],
      challengePlatform: 'Frontend Mentor',
      url: 'https://sameemanasrin.github.io/rock_paper_scissors_game/',
    },
  ],

  experienceInfo: [
    {
      position: 'SENIOR SOFTWARE ENGINEER',
      company: '@Capgemini • DBS • July, 2023 - Nov, 2024',
      desc: 'Led development of new features in a full-stack Angular app, enhancing functionality and user experience through effective architecture and implementation. Tech Stack: Angular, TypeScript, HTML, CSS, Angular Material, PrimeNg, REST APIs, Git, RxJs',
    },
    {
      position: 'SOFTWARE ENGINEER',
      company: '@Capgemini • DBS • July, 2021 - July, 2023',
      desc: 'Enhanced Angular projects with full-stack capabilities, developing StreamSets pipelines for data extraction and integrating back-end API with Spring Boot. Tech Stack: Angular, StreamSets, Spring Boot, REST API',
    },
    {
      position: 'SOFTWARE ENGINEER INTERN,',
      company: '@Capgemini • Mar, 2021 - Jul, 2021',
      desc: 'Mastered full-stack development with Angular for dynamic UIs and Java Spring Boot for strong backend solutions, creating responsive, high-performance applications that balance functionality, usability, and scalability. Project Github link - Front-end, Back-end',
    },
  ],
};
